### ISSUE TITLE
regex doesn't escape interpolated string

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/minerva-browser#1]
A regexp is built by string concatenation here:
https://github.com/labsyspharm/minerva-browser/blob/master/links_alias.js#L27

The issue is when `a` contains regex metacharacters. Whenever you interpolate a variable into a regex, you need to escape any metacharacters:
```javascript
    const match_a = RegExp('^' + a.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '$', 'gi');
```
Probably worth a scan through the code to catch any other instances of something similar.

**Comment by thejohnhoffer** [comment]
Closed with https://github.com/labsyspharm/minerva-browser/commit/b095b903d63a33591f1d064e0bbee0d19ba895e1
