### ISSUE TITLE
lens opacity

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/minerva-browser#16]
Once the lens has its own UI for drag+drop (#15), add a control to adjust opacity. This supports easier back/forth comparison of the base and lens image layers.

**Comment by thejohnhoffer** [comment]
Now that lensing happens in WebGL, we have much more freedom as to how opacity will be handled. Currently, we have a global alpha parameter, but no UI enabled. Compared to the previous iteration, we have room to also improve the look and usability of the actual lens opacity UI element.
