### ISSUE TITLE
channel descriptions

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/minerva-browser#19]
Add longer-form (but still relatively short) text to channel display. This would typically be used to explain the biological interpretation of a given marker.

**Comment by thejohnhoffer** [comment]
Available in Minerva Browser [v3.3.5](https://github.com/labsyspharm/minerva-browser/releases/tag/v3.3.5).
Tested in Minerva Author [commit `e4c8860`](https://github.com/labsyspharm/minerva-author/commit/e4c88608cb56ebd10fe766cb5ae0b2dd658d2877)/
