### ISSUE TITLE
channel legend info rows collapse to zero height if detail text is empty

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/minerva-browser#35]
If earlier channels don't have detail text but later channels do, the ones without text collapse so the alignment of channel name to detail text is broken. Maybe the simplest thing to do is fill in an `&nbsp;` if the user doesn't provide any detail text.

For example in the story currently published at https://www.cycif.org/data/gray-stic-2/ , the `DNA` channel never has any detail text so the other channels' details are pushed up. First channel group for example:
![image](https://github.com/labsyspharm/minerva-browser/assets/277154/55d4e757-efa1-433b-ab46-ec89df3f8efd)

**Comment by thejohnhoffer** [comment]
Closed with latest release v3.19.2
